<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<definitions 
        xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
        xmlns:tns="http://example.org/" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xmlns="http://schemas.xmlsoap.org/wsdl/" 
        targetNamespace="http://example.org/" 
        name="ImageServerImplService">
    <types></types>
    <message name="uploadImage">
        <part name="data" type="xsd:base64Binary"></part>
    </message>
    <message name="uploadImageResponse">
        <part name="return" type="xsd:string"></part>
    </message>
    <portType name="ImageServicePort">
        <operation name="uploadImage">
            <input message="tns:uploadImage"></input>
            <output message="tns:uploadImageResponse"></output>
        </operation>
    </portType>
    <binding name="ImageServiceBinding" type="tns:ImageServicePort">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="uploadImage">
            <soap12:operation soapAction=""/>
            <input>
                <soap12:body use="literal" namespace="http://example.org/"/>
            </input>
            <output>
                <soap12:body use="literal" namespace="http://example.org/"/>
            </output>
        </operation>
    </binding>
    <service name="ImageService">
        <port name="ImageServicePort" binding="tns:ImageServiceBinding">
            <soap12:address location="http://localhost:9999/ws/image"/>
        </port>
    </service>
</definitions>
