java_library(
    name = "core-streams",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@commons_logging//jar",
        "//components/xml-utils",
        "//components/base64-utils",
    ],
)
