/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License") you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.axiom.om.impl.dom;

import java.util.stream.Stream;

import org.apache.axiom.testutils.suite.MatrixTestFilters;
import org.apache.axiom.ts.dom.w3c.level3.W3CDOMLevel3TestSuite;
import org.junit.jupiter.api.DynamicNode;
import org.junit.jupiter.api.TestFactory;

public class W3CDOMLevel3ImplementationTest {
    @TestFactory
    Stream<DynamicNode> tests() {
        return W3CDOMLevel3TestSuite.create(DOMTests.FACTORY, DOMTests.UNSUPPORTED_FEATURES)
                .toDynamicNodes(
                        MatrixTestFilters.builder()
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/canonicalform06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/checkcharacternormalization01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode07)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode10)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode11)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode12)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentadoptnode14)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentgetdoctype01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentgetdocumenturi01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentgetxmlstandalone05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentgetxmlversion03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument07)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument10)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument11)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument12)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentnormalizedocument13)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentsetstricterrorchecking01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentsetstricterrorchecking02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentsetxmlversion01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/documentsetxmlversion05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigcanonicalform1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigcdatasections1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigcheckcharacternormalization1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigcomments1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigdatatypenormalization1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigelementcontentwhitespace1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigentities1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigerrorhandler1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigerrorhandler2)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfiginfoset1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfignamespacedeclarations1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfignamespaces1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfignormalizecharacters1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigparameternames01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigschemalocation1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigschematype1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigsplitcdatasections1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigurationcansetparameter01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigurationcansetparameter02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigurationcansetparameter04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigurationcansetparameter06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigurationgetparameter01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigurationgetparameter02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigvalidate1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigvalidateifschema1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domconfigwellformed1)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domimplementationgetfeature01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domimplementationgetfeature02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domimplementationgetfeature03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domimplementationgetfeature05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domimplementationgetfeature06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domstringlistcontains01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domstringlistcontains02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domstringlistgetlength01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domstringlistitem01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/domstringlistitem02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementcontentwhitespace01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributenode01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributenode04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributenode08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributenode09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens10)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens11)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens13)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/elementsetidattributens14)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/entities03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/handleerror01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/handleerror02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/hasFeature03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/hasFeature04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset07)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/infoset09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/namespacedeclarations01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/namespacedeclarations02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeappendchild01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition07)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition10)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition11)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition12)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition13)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition14)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition15)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition16)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition17)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition18)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition19)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition20)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition21)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition25)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition30)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition31)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition32)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition33)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition34)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition35)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition36)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition37)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition38)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition39)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodecomparedocumentposition40)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature07)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature09)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature10)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegetfeature11)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegettextcontent04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegettextcontent15)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegettextcontent16)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodegettextcontent19)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeinsertbefore02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeinsertbefore05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeinsertbefore14)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeinsertbefore25)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeisequalnode05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeisequalnode10)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodeisequalnode11)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/noderemovechild19)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodereplacechild13)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodereplacechild28)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodereplacechild31)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodereplacechild40)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodesettextcontent12)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodesetuserdata01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/nodesetuserdata02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/normalizecharacters01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/normalizecharacters03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/normalizecharacters05)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/textreplacewholetext06)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/textreplacewholetext08)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/userdatahandler01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/userdatahandler02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/userdatahandler03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/userdatahandler04)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/wellformed01)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/wellformed02)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/wellformed03)")
                                .add(
                                        "(id=http://www.w3.org/2001/DOM-Test-Suite/level3/core/wellformed04)")
                                .build());
    }
}
